"""update table item field description

Revision ID: 0094ad012e81
Revises: 7b6e6df26402
Create Date: 2024-02-27 12:19:11.845471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0094ad012e81'
down_revision: Union[str, None] = '7b6e6df26402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('item', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('discription', sa.VARCHAR(), nullable=True))
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
